# Generated by Django 4.2.2 on 2023-06-28 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='capa',
            field=models.ImageField(blank=True, default='', upload_to='livros/capas/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='livros.category'),
        ),
    ]
