# Generated by Django 4.2.2 on 2023-07-08 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0003_alter_livro_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='data_publicacao',
            field=models.DateField(null=True),
        ),
    ]
